core: mbedtls: fix sha512_process data array bound
The 'data' parameter of mbedtls_internal_sha512_process() was declared
as 'const unsigned char data[64]' in lib/libmbedtls/core/hash.c, but
the prototype in mbedtls/sha512.h declares it as
'const unsigned char data[128]' (SHA-512 block size is 128 bytes).

This mismatch triggers a -Werror=array-parameter build failure when
ARM Crypto Extensions are enabled:

  $(call force,CFG_CRYPTO_WITH_CE,y)
  $(call force,CFG_CRYPTO_WITH_CE82,y)

  lib/libmbedtls/core/hash.c:223:29: error: argument 'data' of type
  'const unsigned char[64]' with mismatched bound [-Werror,
  -Warray-parameter]
  lib/libmbedtls/mbedtls/include/mbedtls/sha512.h:144:57:
  note:
  previously declared as 'const unsigned char[128]' here

Fix the definition to use data[128] to match the prototype.

Signed-off-by: ming-jen.chang <ming-jen.chang@mediatek.com>
Signed-off-by: Leo Chen <shf.chen@mediatek.com>
Reviewed-by: Jerome Forissier <jerome.forissier@arm.com>