libmbedtls: fix unrecognized compiler option
Prior to this patch when compiling with clang there an error:
error: unknown warning option '-Wno-unused-functions'; did you mean '-Wno-unused-function'? [-Werror,-Wunknown-warning-option]

Fix this by using -Wno-unused-function instead.

Fixes: dfafe507bbef ("Import mbedtls-3.4.0")
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>