core: tee_svc.c: add missing comma
Add missing comma to fix the following error:

 $ make -s PLATFORM=vexpress-qemu_armv8a CFG_TA_PAUTH=y CFG_MEMTAG=y
 core/tee/tee_svc.c:371:9: error: expected ‘}’ before ‘{’ token
   371 |         {
       |         ^
 core/tee/tee_svc.c:280:44: note: to match this ‘{’
   280 | const struct tee_props tee_propset_tee[] = {
       |                                            ^

Fixes: a0e8ffe9ba8f ("core: add support for MTE")
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>