Update typedefs.checkpatch
Adds missing typedefs from lib/libutee/include/tee_api_types.h to
typedefs.checkpatch. This fixes checkpatch errors such as:

 ERROR: need consistent spacing around '*' (ctx:WxV)
 #807: FILE: lib/libutee/tee_api_arith_mpi.c:773:
 +void TEE_BigIntInitFMMContext(TEE_BigIntFMMContext *context __unused,
                                                     ^
The file is sorted in reverse alphabetical order, otherwise checkpatch
would ignore some entries that have a common radix (such as TEE_BigInt/
TEE_BigIntFMM/TEE_BigIntFMMContext). Not sure if it is expected or if it
will be fixed in upstream checkpatch at some point.

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>