core: ltc: add missing string_ext.h include
Add a missing include <string_ext.h> needed to fix:
core/lib/libtomcrypt/gcm.c: In function ‘crypto_aes_gcm_dec_final’:
core/lib/libtomcrypt/gcm.c:198:13: error: implicit declaration of function ‘consttime_memcmp’ [-Werror=implicit-function-declaration]
  198 |         if (consttime_memcmp(dst_tag, tag, tag_len) != 0)

Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>
Acked-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Etienne Carriere <etienne.carriere@foss.st.com>