core: arm64: support relocation type R_AARCH64_ABS64 (257)
If a 64-bit TA contains relocations of type R_AARCH64_ABS64, OP-TEE
refuses to load it and logs the following error:

  ERROR:   TEE-CORE: Unknown relocation type 257

This relocation type does not seem to happen in our test applications,
but someone has experienced the issue after linking a TA against a
third-party static library [1]. I could reproduce the issue by
compiling the hello_world TA with -fPIC instead of -fpie. This simple
change generates *one* R_AARCH64_ABS64 in the TA ELF file.

This commit adds the necessary code to support R_AARCH64_ABS64.

[1] https://github.com/OP-TEE/optee_os/issues/1399

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (qemu_v8)
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>