core: ltc: always define LTC_DER
tomcrypt_private.h uses ltc_asn1_list which is defined in tomcrypt_pk.h
only when LTC_DER is defined. Since tomcrypt_private.h is included
unconditionally in some files such as core/lib/libtomcrypt/tomcrypt.c
it needs to compile with no error. Therefore add -DLTC_DER.

Fixes the following error:

 $ make CFG_CRYPTO=n CFG_REE_FS=n
 ...
  CC      out/arm-plat-vexpress/core/lib/libtomcrypt/tomcrypt.o
 In file included from core/lib/libtomcrypt/tomcrypt.c:9:
 core/lib/libtomcrypt/src/headers/tomcrypt_private.h:64:4: error: unknown type name ‘ltc_asn1_list’
    64 |    ltc_asn1_list *enc_data;
       |    ^~~~~~~~~~~~~
 ...

Signed-off-by: Jerome Forissier <jerome@forissier.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
Acked-by: Etienne Carriere <etienne.carriere@linaro.org>