libutils: add stubs for pthread functions
When building with GCC 11.3.1 [1], the linker reports undefined symbols
in the C++ test TA:

 $ make 2>&1 | grep -E "(in function|undefined reference)" | sed 's@.*/@@'
 libstdc++.a(eh_alloc.o): in function `(anonymous namespace)::pool::free(void*) [clone .constprop.0]':
 gthr-default.h:749: undefined reference to `pthread_mutex_lock'
 gthr-default.h:779: undefined reference to `pthread_mutex_unlock'
 libstdc++.a(eh_alloc.o): in function `(anonymous namespace)::pool::allocate(unsigned long) [clone .constprop.0]':
 gthr-default.h:749: undefined reference to `pthread_mutex_lock'
 gthr-default.h:779: undefined reference to `pthread_mutex_unlock'
 libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__gthread_mutex_lock':
 gthr-default.h:749: undefined reference to `pthread_mutex_lock'
 libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__gthread_mutex_unlock':
 gthr-default.h:779: undefined reference to `pthread_mutex_unlock'
 [more of the same follow]

To fix that issue, introduce no-op stubs as weak symbols in libutils.
Doing so is valid because TAs are single threaded and non-reentrant.

Link: [1] https://developer.arm.com/-/media/Files/downloads/gnu/11.3.rel1/binrel/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Etienne Carriere <etienne.carriere@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>
Acked-by: Sumit Garg <sumit.garg@linaro.org>