Revert "ci: shippable: enable parallel build"
This reverts commit cf012d013e2e2a3cc7d1e8969bcdb44c4dcc84ab.

mk: cleanvars.mk: clean spec-srcs var

Clean $(spec-srcs) variable, as the value can be accumulated in
ta/mk/build-user-ta.mk

Fixes linking issues when multiple TAs are compiled as Early TAs
(using CFG_IN_TREE_EARLY_TAS)

$ make V=1
...
out/arm/ta/avb/user_ta_header.o:(.data+0x0): multiple definition of `trace_level'
out/arm/ta/avb/user_ta_header.o:(.data+0x0): first defined here
out/arm/ta/avb/user_ta_header.o: In function `tahead_get_trace_level':
optee_os/out/arm/export-ta_arm32/src/user_ta_header.c:102: multiple definition of `trace_ext_prefix'
out/arm/ta/avb/user_ta_header.o:optee_os/out/arm/export-ta_arm32/src/user_ta_header.c:102: first defined here
out/arm/ta/avb/user_ta_header.o: In function `tahead_get_trace_level':
optee_os/out/arm/export-ta_arm32/src/user_ta_header.c:102: multiple definition of `ta_head'
out/arm/ta/avb/user_ta_header.o:optee_os/out/arm/export-ta_arm32/src/user_ta_header.c:102: first defined here
out/arm/ta/avb/user_ta_header.o: In function `tahead_get_trace_level':
optee_os/out/arm/export-ta_arm32/src/user_ta_header.c:102: multiple definition of `ta_heap'
out/arm/ta/avb/user_ta_header.o:optee_os/out/arm/export-ta_arm32/src/user_ta_header.c:102: first defined here
out/arm/ta/avb/user_ta_header.o: In function `tahead_get_trace_level':
optee_os/out/arm/export-ta_arm32/src/user_ta_header.c:102: multiple definition of `ta_heap_size'
out/arm/ta/avb/user_ta_header.o:optee_os/out/arm/export-ta_arm32/src/user_ta_header.c:102: first defined here
out/arm/ta/avb/user_ta_header.o: In function `tahead_get_trace_level':
optee_os/out/arm/export-ta_arm32/src/user_ta_header.c:102: multiple definition of `ta_props'

Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>

ta: link.mk: evaluate $(sm) values in targets

$(sm) var isn't properly evalutated as the link.mk is included (final
evaluation is done when the rule is triggered). Add dynamic target
generation based on the current value of $(sm)

Fixes: https://github.com/OP-TEE/optee_os/issues/2537
Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>