libutils: introduce MAX_UNSAFE() and MIN_UNSAFE()
This change allows one to use MAX_UNSAFE() and MIN_UNSAFE() macros
in particular conditions where MAX()/MIN() macros fail to build
from C source file implementation with error traces as below:

In file included from core/arch/arm/include/arm.h:8:0,
                 from core/arch/arm/include/kernel/thread.h:11,
                 from core/arch/arm/kernel/asm-defines.c:7:
lib/libutils/ext/include/util.h:24:16: error: missing binary operator before token "("
  (__extension__({ __typeof__(a) _a = (a); \
                ^
core/arch/arm/plat-stm/./platform_config.h:190:25: note: in expansion of macro ‘MAX’
 #define STM_SECDDR_END  MAX(TZSRAM_BASE + TZSRAM_SIZE, \
                         ^~~
core/arch/arm/plat-stm/./platform_config.h:204:6: note: in expansion of macro ‘STM_SECDDR_END’
 #if (STM_SECDDR_END < 0x80000000ULL)
      ^~~~~~~~~~~~~~
make: *** [out/core/include/generated/.asm-defines.s] Error 1

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>