core: ltc: add missing <string_ext.h>
Add missing #include <string_ext.h> to fix build  errors such as:

 core/lib/libtomcrypt/ccm.c: In function ‘crypto_aes_ccm_dec_final’:
 core/lib/libtomcrypt/ccm.c:205:6: error: implicit declaration of function ‘consttime_memcmp’ [-Werror=implicit-function-declaration]
   205 |  if (consttime_memcmp(dst_tag, tag, tag_len) != 0)
       |      ^~~~~~~~~~~~~~~~

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Acked-by: Jens Wiklander <jens.wiklander@linaro.org>