core: core.mk: Fix compiler error due to TEE_IMPL_GIT_SHA1 type
If the upper 32 bits of TEE_IMPL_GIT_SHA1 happen to be zero or
CFG_OS_REV_REPORTS_GIT_SHA1 is off, the compiler will complain:

core/arch/arm/kernel/thread_spmc.c:836:49: error: right shift count >= width of type [-Werror=shift-count-overflow]
  836 |                               TEE_IMPL_GIT_SHA1 >> 32);
      |                                                 ^~

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>