libtomcrypt: ECC code depends on ASN1 routines
Fixes:
 $ make -j8 -s CFG_CRYPTO_{DSA,RSA}=n
 [...]libtomcrypt.a(ecc_sign_hash.o): In function `ecc_sign_hash':
 [...]ecc_sign_hash.c:166: undefined reference to
 `der_encode_sequence_multi'

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>