core: fix undefined reference to ubsan function
Add UBSan handler  __ubsan_handle_invalid_builtin, which support __builtin*
functions validation. In some cases when __builtin functions are used,
undefined behaviour might be triggered by invalid arguments. E.g. passing 0 as
the argument to __builtin_ctz or __builtin_clz invokes undefined behavior and is
diagnosed by UBSan.

Signed-off-by: Aleksandr Iashchenko <alexhoppus111@gmail.com>