core: fix compile error when CFG_TEE_CORE_MALLOC_DEBUG=y
When CFG_TEE_CORE_MALLOC_DEBUG is enabled, but CFG_TEE_CORE_DEBUG is
not, the compiler complains about unused parameters/functions. Fix them
by adding __maybe_unused qualifiers.

lib/libutils/isoc/bget_malloc.c: In function ‘assert_header’:
lib/libutils/isoc/bget_malloc.c:688:44: error: unused parameter ‘hdr’ [-Werror=unused-parameter]
 static void assert_header(struct mdbg_hdr *hdr)
                                            ^
lib/libutils/isoc/bget_malloc.c: At top level:
lib/libutils/isoc/bget_malloc.c:595:16: error: ‘bget_buf_size’ defined but not used [-Werror=unused-function]
 static bufsize bget_buf_size(void *buf)
                ^
cc1: all warnings being treated as errors

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>
Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>