plat-ti: fix build errors
Fixes build error with PLATFORM=ti-dra7xx and PLATFORM=ti-am43xx:

 error: conflicting types for ‘sm_platform_handler’
  bool sm_platform_handler(struct sm_ctx *ctx)
       ^~~~~~~~~~~~~~~~~~~

Fixes: aea0999e2360 ("core: explicit return value for sm_platform_handler()")
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>